//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ebook.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> AuthorId_ { get; set; }
        public string Isbn { get; set; }
        public Nullable<int> PublisId { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public Nullable<int> NumberOfPages { get; set; }
        public Nullable<int> FormatId { get; set; }
        public string Edition { get; set; }
        public string Description { get; set; }
        public string BookCoverPath { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public Nullable<int> BookTypeId { get; set; }
        public Nullable<int> ContentId { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Format Format { get; set; }
        public virtual BookType BookType { get; set; }
        public virtual Content Content { get; set; }
        public virtual Format Format1 { get; set; }
    }
}
